package com.example.sweater;

import com.example.sweater.domain.Message;
import com.example.sweater.repository.MessageRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.Map;

@Controller
public class GreetingController {
    /*
        This means to get the bean called userRepository
        Which is auto-generated by Spring, we will use it to handle the data
     */
    @Autowired
    private MessageRepository messageRepository;
    /*
        Lesson_3 CSRF
    Spring MVC будет дополнительно отдавать в контролере доп параметры, и они будут переходить в шаблон,
    для этого добавляется невидимое поле в каждой форме (mustache или html)
     */

    @GetMapping("/")
    public String greeting(Map<String, Object> model) {
        return "greeting";
    }
    @GetMapping("/main")
    public String index(Map<String, Object> model) {
        return "main";
    }

    @PostMapping("/main")
    public String add(@RequestParam String text, @RequestParam String tag, Map<String, Object> model) {
        //Добавляю в список сообщения по нажатию кнопки
        Message message = new Message(text, tag);
        messageRepository.save(message);

        //Вывод списка (так делать не надо, это должно быть разделено на /add и /all)
        Iterable<Message> messages = messageRepository.findAll();
        model.put("messages", messages);
        return "main";
    }

    //Указывается в параметре аннотации mapping из html файла 'action="filter"'
    @PostMapping("filter")
    public String filter(@RequestParam String filter, Map<String, Object> model) {
        //У меня нет метода поиска по тегу, тогда создаю его в MessageRepository
        Iterable<Message> messages;
        if (filter != null && !filter.isEmpty()) {
            messages = messageRepository.findByTag(filter);
        } else {
            messages = messageRepository.findAll();
        }

        model.put("messages", messages);
        return "main";
    }
}
